version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
    - 5434:5432
    container_name: PostgresSantexDev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: santex
    networks:
      - santex

networks:
  santex:
